### ISSUE TITLE
this page is broke content/posts/2023/nixos-explained.md

### ISSUE THREAD

**Issue by bckelley** [ChrisTitusTech/website#145]
Numerous people on yt experiencing 404 errors

**Comment by bckelley** [comment]
page is back up

**Comment by Man2Dev** [comment]
thanks Chris this will save me so much time

**Comment by Ashdemai** [comment]
I don't think nowadays it's wise to rely on YouTube to store videos. I know it's a bummer but you should probably plan on having the videos hosted locally. Especially long informative live streams

**Comment by bckelley** [comment]
> I don't think nowadays it's wise to rely on YouTube to store videos. I know it's a bummer but you should probably plan on having the videos hosted locally. Especially long informative live streams

@ChrisTitusTech correct me if I'm wrong here but I do believe I remember him saying something about self-hosting them as well.

**Comment by ChrisTitusTech** [comment]
> > I don't think nowadays it's wise to rely on YouTube to store videos. I know it's a bummer but you should probably plan on having the videos hosted locally. Especially long informative live streams
> 
> @ChrisTitusTech correct me if I'm wrong here but I do believe I remember him saying something about self-hosting them as well.

Correct, I have 106tb of local redundant storage

**Comment by ThisNekoGuy** [comment]
Haven't finished watching it yet (mainly because I don't have a spare machine for trying NixOS on at the moment anyway and my main machine is an Arch-box) but I've wanting to know if NixOS can be configured to run on MUSL rather than glibc...

**Comment by ChaosNicro** [comment]
I'm on Opensuse Leap at the moment and might have to hop soon, since they are moving to a static image + containers base with ALP. Package comparability is through the roof with Nix and the shell seems great for building stuff from source without cluttering your system.
@ChrisTitusTech Did you ever talk about static image distros? 
I just can't see them working well with something as customized as an everyday desktop with X number of extra packages, each overlayed separately on the base image.
It's similar to the "everything you install is a flatpak"-distros.

**Comment by gr007-40** [comment]
@ChrisTitusTech, I have been using nix for a good few weeks and everything has been all good and great but one thing is very upsetting. I just don't like the way nix handles dynamic linking. If I want to just download a binary and want to run it, in a lot of cases it will cause a linking issue. This also prevents [mason](https://github.com/williamboman/mason.nvim) from downloading lsp servers on it's own and manage them in my nvim configuration. I saw some workarounds or solutions like using [nix-ld](https://github.com/thiagokokada/nix-alien) but i think this issue needs to be fixed from the base. I know the nix team has done an absolute awesome of a job by putting together such a declarative and reproducible distro. I want to know if i can somehow use another package manager in nixos. or any distro based on arch-linux that hopes to achieve such reproducibility. And lastly, thank you for always bringing out such practical contents.

**Comment by mahmoud-shihab** [comment]
Dumb Question, but do you have a way to install python such that you can pip install packages?
What about anaconda?

**Comment by Leowhyx** [comment]
Intresting post
