### ISSUE TITLE
Add rule to Cloudflare to minify page responses

### ISSUE THREAD

**Issue by obfuscated-loop** [ChrisTitusTech/website#181]
I noticed that you're using [Cloudflare Pages to deploy the website](https://github.com/ChrisTitusTech/website/runs/21656314760) - I usually use a module called [`mod_pagespeed`](https://www.modpagespeed.com/) on my apache servers to minify responses and do other optimisation stuff.

Cloudflare Pages has an option for minifying the response payload within their dashboard at: https://dash.cloudflare.com/?to=/:account/:zone/speed/optimization (see https://www.answeroverflow.com/m/1116304720353579068).

I think it may be worth turning `Auto Minify` on, and using the other optimisation tools of Cloudflare to improve response/rendering times on the website.

**Comment by digitalsparky** [comment]
In this case, Hugo already has a minify step, looks like all the CSS/JS is already being minified, so all @ChrisTitusTech has to do is build using the --minify flag in order to get HTML minified as well.

**Comment by digitalsparky** [comment]
@ChrisTitusTech please change the hugo build command to:

```
HUGO_ENV="production" hugo --gc --minify .
```

**Comment by ChrisTitusTech** [comment]
Thanks for letting me know about this. I missed the hugo build command to minify it. It's added now and it should now be properly minifying things.
