### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by Davidhsherman13** [ChrisTitusTech/website#196]
Today, I purchased the package. I am running 23H2 or build 22631.3447. (I am running Windows Defender)
I made the exception under the readme to exclude files and folder. 
All I get is a dialog box that "shows bytes" and closes. Prior to buying the product, I could only get the download is when I installed the product the day I purchased this machine about a month ago.

What can I do to get the purchased product to work?

PS. I think that Windows defender thinks that the file is a virus and puts the file in quarantine. Is this true? How do I stop this?

thank.

PS. 
![chris#1](https://github.com/ChrisTitusTech/website/assets/123390505/2bc4a53d-9884-4e33-969e-a4ecf28ca459)

**Comment by ChrisTitusTech** [comment]
1. Select Start  , then open Settings  . Under Privacy & security  , select Virus & threat protection.
2. Under Virus & threat protection settings, select Manage settings, and then under Exclusions, select Add or remove exclusions.
3. Where to add an exclusion in the Windows Security app.

![image](https://github.com/ChrisTitusTech/website/assets/7896101/110d13dc-4fa2-4833-b6e0-7f1ef4f21c44)

4. Select Add an exclusion, and then select from files, folders, file types, or process. A folder exclusion will apply to all subfolders within the folder as well.

**I recommend making an new folder called winutil and excluding it**
