### ISSUE TITLE
posts page don't show posts

### ISSUE THREAD

**Issue by ahmadkakarr** [ChrisTitusTech/website#4]
**https://christitus.com/posts/ this page is empty because you set type=post in front matter just remove that and your posts will show up here.**

can you please tell me how you are doing optimizations on this theme and your customization maybe a post or video... anything that you are doing special about this theme or hugo.... thanks...

**Comment by mrfoxie** [comment]
> **https://christitus.com/posts/ this page is empty because you set type=post in front matter just remove that and your posts will show up here.**
> 
> can you please tell me how you are doing optimizations on this theme and your customization maybe a post or video... anything that you are doing special about this theme or hugo.... thanks...

I can help you with that if you want because I'm running the same same theme for my site [Blogger](https://github.com/mrfoxie/mistrysiddh)
